version: "3.9"
services:
  api:
    build: .
    container_name: video-transcoder
    ports:
      - "8081:8080"   # host:container
    environment:
      - JWT_SECRET=supersecret
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./data:/app/data
    restart: unless-stopped
